language: node_js
node_js:
 - "node"

install:
  - npm install
  - npm install mocha --save
  - npm install chai --save

stages:
- name: Staging
- name: Production

jobs:
  include:
  - stage: Staging
    script: "mocha server/test/teste.js"

  - stage: Deploy
    script: skip
    deploy:
      provider: heroku
      api_key: 
        secure: $HEROKU_API_KEY
      app: wemoney
      on: 
        branch: master

notifications:
  email:
    recipients:
    - mail@gmail.com
    on_success: change
    on_failure: always
